<a href="https://colab.research.google.com/github/Arunsky29/Python/blob/main/NUMPY_30_12_%26_31_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INDEXING

In [78]:
arr=np.array([1,2,3,4])
print(arr[2])

3


In [79]:
arr[2] = 33
print(arr)

[ 1  2 33  4]


In [80]:
arr_2d=np.array([[1,2,3,4],[2,3,49,16],[22,33,44,55]])
print(arr_2d)

[[ 1  2  3  4]
 [ 2  3 49 16]
 [22 33 44 55]]


In [85]:
arr_3d=np.array([[[1,2,3,4],[8,9,7,6],[7,6,5,4]],[[8,9,7,7],[8,9,7,6],[7,6,5,4]]])
arr_3d[0][2][0]

7

# SLICING

In [77]:
num=np.array([5,6,3,2,24,5,7,98,76,54,3])
print(num)
print(num[3:8])
print(num[3:])
print(num[:5])
print(num[-5:-1])

[ 5  6  3  2 24  5  7 98 76 54  3]
[ 2 24  5  7 98]
[ 2 24  5  7 98 76 54  3]
[ 5  6  3  2 24]
[ 7 98 76 54]


# Array Manipulations


In [ ]:
import numpy as np

In [ ]:
arr_2d=np.array([[1,2,3,4],[]])

In [ ]:
arr_2d[ arr_2d % 2==0]

In [ ]:
x=np.array([2,3])
y=np.array([7,8])
sum=np.add(x,y)
print(sum)

[ 9 11]


In [ ]:
a=np.array([1,2,3,4])
print (a**2)

[ 1  4  9 16]


In [ ]:
sal=np.array([20000,35000,60000])
print(sal+2000)

[22000 37000 62000]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.transpose)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<built-in method transpose of numpy.ndarray object at 0x79704d2d6c70>


In [ ]:
i=np.eye(6)
print(i)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
m=np.ones((3,3))
print(m)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
m=np.ones((3,3),dtype='i')
print(m)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
print(i.astype('bool'))

[[ True False False False False False]
 [False  True False False False False]
 [False False  True False False False]
 [False False False  True False False]
 [False False False False  True False]
 [False False False False False  True]]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[2,3,4],[5,6,7],[8,9,10]])
print(np.matmul(a,b))

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


# Array Broadcasting

In [ ]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.arange(5)+4

array([4, 5, 6, 7, 8])

In [ ]:
k=np.ones((3,3))+np.arange(3)
print(k)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
np.arange(3).reshape(3,1)

array([[0],
       [1],
       [2]])

In [ ]:
np.arange(3)+np.arange(3).reshape(3,1)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
a=np.array([1,2,3])
b=np.array([[4],[5],[6]])
c=a+b
print(c)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


# Array Broadcasting 2

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([5,6])
c=a+b
print(c)

[[ 6  8]
 [ 8 10]]


In [ ]:
# Floating Point Broadcasting

a=np.array([[0.0, 0.0, 0.0],[10.0, 10.0, 10.0],[20.0, 20.0, 20.0],[30.0, 30.0, 30.0]])
b=np.array([1.0, 2.0, 3.0])
print(a+b)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


# Reshaping = Temp Changes

In [ ]:
arr=np.arange(12)
print(arr)
arr.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11]


(12,)

In [ ]:
arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
arr.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
print(arr.reshape(2,3,2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [ ]:
a=np.arange(6).reshape(3,2)
print(a)

[[0 1]
 [2 3]
 [4 5]]


# Flattening = Higher Dimension to Lower Dimension(3d-1d, etc)

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [ ]:
k= print(arr.reshape(-1))

[1 2 3 4 5 6]


# Resizing = Changes Original Data

In [ ]:
data=np.array([10,20,30,40,50,60,70,80])
print('Original \n',data)
print('\n Resized Data')
data.resize(4,2)
print(data)

Original 
 [10 20 30 40 50 60 70 80]

 Resized Data
[[10 20]
 [30 40]
 [50 60]
 [70 80]]


# STACK - JOIN,MERGE,COMBINE(2 1D [ ] AND [ ] ARRAY COMBINES = 2D ARRAY[[ ]])
# TYPES
# STACK - COMBINE
# VSTACK - VERTICAL STACK
# HSTACK - HORIZONTAL STACK
# DSTACK - DEPTH STACK

In [5]:
import numpy as np
x = np.array([1,2,3])
y = np.array([3,6,9])
print(np.stack((x,y)))

[[1 2 3]
 [3 6 9]]


In [6]:
print(np.stack((x,y),axis=0)) #row

[[1 2 3]
 [3 6 9]]


In [8]:
print(np.stack((x,y),axis=1)) #column

[[1 3]
 [2 6]
 [3 9]]


In [9]:
print(np.vstack((x,y))) #vstack - row

[[1 2 3]
 [3 6 9]]


In [13]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [10]:
print(np.hstack((x,y))) #hstack

[1 2 3 3 6 9]


In [12]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [11]:
print(np.dstack((x,y))) #dstack - vertical(3d)

[[[1 3]
  [2 6]
  [3 9]]]


In [14]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.dstack((a,b)))

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [15]:
# Dimensions are not Same = Value Error
a=np.array([[1,2],[3,4]])
b=np.array([[1],[2]]).reshape(1,2) # 1row and 2 column
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [1 2]]


# SPLIT

In [19]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
spl=np.split(arr,3)
print('array = \n',arr)
print('split = ',spl)

array = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
split =  [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [20]:
spl=np.split(arr,3,axis=0)
print(spl)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [21]:
spl=np.split(arr,3,axis=1)
print(spl)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [22]:
sp2=np.split(arr,indices_or_sections=[1],axis=1)
print(sp2)

[array([[1],
       [4],
       [7]]), array([[2, 3],
       [5, 6],
       [8, 9]])]


In [23]:
sp2=np.split(arr,indices_or_sections=[2],axis=1)
print(sp2)

[array([[1, 2],
       [4, 5],
       [7, 8]]), array([[3],
       [6],
       [9]])]


In [24]:
for col in sp2:
  print(col)

[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


# TRIGNOMETRIC FUNCTIONS ON NUMPY

In [31]:
print(np.sin(90),
np.cos(0),
np.tan(0)) # radian values

0.8939966636005579 1.0 0.0


In [34]:
arr=np.array([0,45,60])
print(np.tan(arr * np.pi/180)) # degree values

import math
math.sqrt(3) #tan60deg

[0.         1.         1.73205081]


1.7320508075688772

# EXPONENTIAL FUNCTIONS
# LOGARITHMIC FUNCTIONS
# STATISTICAL FUNCTIONS

In [35]:
print(math.exp(3))
print(np.exp(3))

20.085536923187668
20.085536923187668


In [37]:
# Logarithmic Functions

np.log(1)

0.0

In [39]:
num=np.array([1,2,3,4,5])
print(np.log(num))
print(np.log10(num))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]


In [44]:
# STATISTICAL FUNCTIONS
import statistics as s
print(s.mean([10,20,30])) #mean - 10+20+30/3(avg)
print(np.mean([10,20,30]))

20
20.0


In [46]:
# median - sort then middle value
print(s.median([12,3,4,6,10]))
print(np.median([12,3,4,6,10]))

6
6.0


In [50]:
a=np.array([[1,2],[3,4]])
print(np.std(a)) # Standard Deviation
print(np.var(a)) # Variance
print(np.sum(a)) # Array Aggregations
print(np.min(a))
print(np.max(a))

1.118033988749895
1.25
10
1
4


In [52]:
arr=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
arr

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [53]:
# Sorting
arr=np.array([22,33,4,11,66])
np.sort(arr)

array([ 4, 11, 22, 33, 66])

In [59]:
arr=np.matrix([[1,12,3],[74,25,16],[87,18,9]])
print(np.sort(arr)) # Ascending Row Wise
print(arr[::-1]) # Single Dimension only works in descending order sorting

[[ 1  3 12]
 [16 25 74]
 [ 9 18 87]]
[[87 18  9]
 [74 25 16]
 [ 1 12  3]]


# SEARCHING

In [62]:
# searchsorted - Indexing and Sorting
arr=[2,3,4,5,6]
print('input',arr)
arrr=[12,33,4,15,76]
output=np.searchsorted(arr,4)
out=np.searchsorted(arrr,4)
print(output)
print(arrr)
print(out)

input [2, 3, 4, 5, 6]
2
[12, 33, 4, 15, 76]
0


# ADVANCED INDEXING

In [63]:
# Indexed Array
a=np.arange(10,1,-2)
print(a)

[10  8  6  4  2]


In [64]:
# Indexes are specifies inside np.array method
newarr=a[np.array([3,1,2])]
print(newarr)

[4 8 6]


In [66]:
# Fancy Indexing
arr=np.array([23,17,55,76,12,33,2,99]) #1D
print('old = ',arr)
indices=[1,3,6]
newvalues=[10,20,30] #insert
arr[indices]=newvalues
print('new = ',arr)

old =  [23 17 55 76 12 33  2 99]
new =  [23 10 55 20 12 33 30 99]


In [75]:
arr=np.array([[1,2,3],[15,7,19],[63,55,33]]) #2D
print('Array = \n',arr)
# Specific Rows
rows=arr[[0,2],:]
print('rows = \n',rows)
# Specific Column
column=arr[:,[0,2]]
print('column = \n',column)

Array = 
 [[ 1  2  3]
 [15  7 19]
 [63 55 33]]
rows = 
 [[ 1  2  3]
 [63 55 33]]
column = 
 [[ 1  3]
 [15 19]
 [63 33]]
